# Zuul routing configuration
# {ms-state-api} is the spring application name
# {path} is our resource name


zuul:
  routes:
    ms-state-api:
      path: /api/state/**
      url: http://localhost:8080/api/state
      
#above configuration means all requests from the UI that starts with “/api/state/” will be routed to our ms-state-api Resource server at http://localhost:8080/api/state/      